services:
  - type: web
    name: cyberlens-api
    env: python
    rootDir: cyberlens/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free